### PR TITLE
Patch so master to master

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @danielepolencic just realised this never got merged to master - deepTranslate middleware. I have patched from so-master so this can be safely merged to master and the branch deleted.

**Comment by easternbloc** [comment]
LGTM. @danielepolencic are you happy for me to merge?

**Comment by danielepolencic** [comment]
**DISCLAIMER**: I'm grumpy old man.

> Using the translation key `fields.field-name.label` will return different values in different situations depending on the values of named fields.

I'm concerned we're reimplementing fork in translations? If that is the case, this scenario should be handled with forks.

Having a value being returned based on the context sounds very error prone and difficult to comprehend.

**Comment by easternbloc** [comment]
> I'm concerned we're reimplementing fork in translations? If that is the case, this scenario should be handled with forks.

Appreciate this and tbh that was my initial thought. But this can be very useful in scenarios such as selecting multiple things on one page and then being able to talk about them collectively on the following pages.

Tbh it's likely to have less caveats than forking which is a bit of a mare.

**Comment by joefitter** [comment]
> Tbh it's likely to have less caveats than forking which is a bit of a mare.

This was to avoid having to fork in these situations, which would result in a whole new step, with a different url, with a set of whole new fields, and the only difference is the label is in the past tense or a plural.

I added this as a middleware so its an optional feature and if the end developer would prefer to fork this is still possible.

**Comment by JoeChapman** [comment]
LGTM

**Pull request merged**
